# API Proxy ClusterIP 서비스 — 클러스터 내부에서만 접근 가능
# 샌드박스 Pod → api-proxy.claudecode-terminal.svc.cluster.local:8080

apiVersion: v1
kind: Service
metadata:
  name: api-proxy
  namespace: claudecode-terminal
  labels:
    app: api-proxy
spec:
  type: ClusterIP
  selector:
    app: api-proxy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
