# RBAC 설정 - 웹 터미널 서비스가 K8s API를 통해 샌드박스 Pod를 관리하기 위한 권한 정의
# ServiceAccount, Role, RoleBinding으로 구성
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-terminal-sa
  namespace: claudecode-terminal
  labels:
    app.kubernetes.io/part-of: claudecode-web-terminal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-terminal-role
  namespace: claudecode-terminal
  labels:
    app.kubernetes.io/part-of: claudecode-web-terminal
rules:
  # 사용자 샌드박스 Pod의 생성, 조회, 삭제, 감시를 위한 권한
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete", "watch"]
  # 샌드박스 Pod 내부에서 명령어를 실행하기 위한 exec 권한
  # WebSocket 업그레이드가 GET으로 시작되므로 get + create 모두 필요
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  # 샌드박스 Pod의 로그를 조회하기 위한 권한
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  # 참고: secrets 권한은 의도적으로 제거됨.
  # API 키는 프록시 서비스가 자체 관리하며, 웹 터미널 서비스가 시크릿에 접근할 필요 없음.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-terminal-binding
  namespace: claudecode-terminal
  labels:
    app.kubernetes.io/part-of: claudecode-web-terminal
subjects:
  - kind: ServiceAccount
    name: web-terminal-sa
    namespace: claudecode-terminal
roleRef:
  kind: Role
  name: web-terminal-role
  apiGroup: rbac.authorization.k8s.io
