# GPU 동작 확인용 테스트 Pod - nvidia-smi 실행 후 종료
# GPU 노드와 device plugin이 설정된 후 이 Pod으로 GPU 접근을 검증
# 사용법: kubectl apply -f gpu-test-pod.yaml && kubectl logs gpu-test -f
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: default
  labels:
    app.kubernetes.io/part-of: papers-with-claudecode
spec:
  restartPolicy: Never
  containers:
    - name: gpu-test
      image: nvcr.io/nvidia/cuda:12.6.3-base-ubuntu24.04
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
